runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  secure: always
  
handlers:
- url: /static
  static_dir: static
  secure: always
  
libraries:
- name: webapp2
  version: latest